In [1]:
import pandas as pd
import numpy as np

from collections import Counter

In [2]:
#on charge le dataframe depuis un format pickle ce qui est plus rapide
data = pd.read_pickle("products")

## On filtre le dataframe sur les indicateurs les plus pertinents pour notre application.
L'objectif est d'explorer et de nettoyer ce nouveau dataframe pour pouvoir exploiter les indicateurs et travailler sur le nutriscore.

Les indicateurs pertinents pour notre application sont :
"code"
"product_name"
"categories"
"generic_name"
"countries"
"main_category"
"nutriscore_score"
"nutriscore_grade"
"energy-kj_100g"
"sugars_100g"
"saturated-fat_100g","sodium_100g","fruits-vegetables-nuts_100g","fiber_100g","proteins_100g"

![Google logo](https://www.researchgate.net/profile/Hassan_Aguenaou/publication/328136107/figure/fig1/AS:679251904835597@1538957682395/Calcul-de-lalgorithme-du-Nutri-Score-le-score-FRSm-HCSP.ppm "google logo")

In [3]:
#On garde seulement les colonnes pertinentes pour notre analyse
products = data[["code","created_datetime","product_name","generic_name","brands","countries_tags"
                 ,"categories_en","main_category_en","nutriscore_score","nutriscore_grade","energy-kj_100g","energy-kcal_100g"
                 ,"sugars_100g","saturated-fat_100g","sodium_100g","fruits-vegetables-nuts_100g","fiber_100g","proteins_100g"]]

In [4]:
products.head()

,code,created_datetime,product_name,generic_name,brands,countries_tags,categories_en,main_category_en,nutriscore_score,nutriscore_grade,energy-kj_100g,energy-kcal_100g,sugars_100g,saturated-fat_100g,sodium_100g,fruits-vegetables-nuts_100g,fiber_100g,proteins_100g
0,0000000000017,2018-06-15 10:38:00+00:00,Vitória crackers,NaN,NaN,en:france,NaN,NaN,NaN,NaN,NaN,375.0,15.0,3.08,0.56,NaN,NaN,7.8
1,0000000000031,2018-10-13 21:06:14+00:00,Cacao,NaN,NaN,en:france,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,000000000003327986,2019-11-19 15:02:16+00:00,Filetes de pollo empanado,NaN,NaN,en:spain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0000000000100,2015-10-11 14:09:21+00:00,moutarde au moût de raisin,NaN,courte paille,en:france,"Groceries,Condiments,Sauces,Mustards",Mustards,18.0,d,936.0,NaN,22.0,2.20,1.84,NaN,0.0,5.1
4,00000000001111111111,2019-06-08 18:56:13+00:00,Sfiudwx,NaN,Watt,en:france,fr:xsf,fr:xsf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
products.describe(include="all")

,code,created_datetime,product_name,generic_name,brands,countries_tags,categories_en,main_category_en,nutriscore_score,nutriscore_grade,energy-kj_100g,energy-kcal_100g,sugars_100g,saturated-fat_100g,sodium_100g,fruits-vegetables-nuts_100g,fiber_100g,proteins_100g
count,1.555491e+06,1555491,1475940,107909,855624,1550329,789898,789898,617047.000000,617047,1.144930e+05,1.171645e+06,1.208137e+06,1.183546e+06,1.202396e+06,8679.000000,454522.000000,1.230710e+06
unique,1.555125e+06,1307562,983358,79119,149085,3281,59689,26794,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,5.926302e+10,2020-04-23 17:22:07+00:00,Aceite de oliva virgen extra,Ice cream,Carrefour,en:france,Snacks,Snacks,NaN,d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2.000000e+00,28,1156,180,13412,677031,32865,32872,NaN,191062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
first,NaN,2012-01-31 14:43:58+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,NaN,2020-12-16 12:26:23+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.149256,NaN,5.821805e+37,7.429025e+06,1.371063e+01,1.149089e+08,7.127955e-01,34.269830,2.969742,8.517973e+00
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.901728,NaN,1.969913e+40,8.031833e+09,2.001887e+01,1.250105e+11,2.962545e+01,36.594116,6.309339,1.084817e+01
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-15.000000,NaN,0.000000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000,-20.000000,-5.000000e+02
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,3.990000e+02,1.010000e+02,7.000000e-01,1.000000e-01,2.400000e-02,0.000000,0.000000,1.200000e+00
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,9.800000e+02,2.630000e+02,3.800000e+00,1.900000e+00,2.180000e-01,20.650000,1.600000,5.900000e+00
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.000000,NaN,1.623000e+03,4.000000e+02,1.930000e+01,7.200000e+00,5.500000e-01,60.000000,3.600000,1.200000e+01
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,6.665559e+42,8.693855e+12,1.350000e+03,1.360000e+14,2.670000e+04,100.000000,2020.000000,2.500000e+03

In [6]:
#On regarde le nombre de données nulles par colonne 
products.isnull().sum()

code                                 0
created_datetime                     0
product_name                     79551
generic_name                   1447582
brands                          699867
countries_tags                    5162
categories_en                   765593
main_category_en                765593
nutriscore_score                938444
nutriscore_grade                938444
energy-kj_100g                 1440998
energy-kcal_100g                383846
sugars_100g                     347354
saturated-fat_100g              371945
sodium_100g                     353095
fruits-vegetables-nuts_100g    1546812
fiber_100g                     1100969
proteins_100g                   324781
dtype: int64

In [7]:
#on trie les valeurs par ordre décroissant de date de création du produit sur Open Foods Facts
products = products.sort_values(by=["created_datetime"], ascending=False)
#on stocke les doublons ayant la date de création la plus ancienne dans le dataframe "doublons"
doublons = products[products["code"].duplicated()]

doublons.count()

code                           366
created_datetime               366
product_name                   355
generic_name                    29
brands                         243
countries_tags                 365
categories_en                  184
main_category_en               184
nutriscore_score               164
nutriscore_grade               164
energy-kj_100g                  16
energy-kcal_100g               314
sugars_100g                    312
saturated-fat_100g             310
sodium_100g                    319
fruits-vegetables-nuts_100g      0
fiber_100g                     175
proteins_100g                  321
dtype: int64

In [8]:
#on garde seulement les lignes uniques ayant la date de création la plus récente
products = products.drop_duplicates(subset=["code"])
#on supprime les lignes ayant des valeurs nulles pour le nutriscore car c'est la valeur centrale de l'analyse
products = products.dropna(subset=['nutriscore_score'])

In [9]:
#On regarde le nombre de valeur nulle
products.isnull().sum()

code                                0
created_datetime                    0
product_name                     2365
generic_name                   532199
brands                         171093
countries_tags                    765
categories_en                       2
main_category_en                    2
nutriscore_score                    0
nutriscore_grade                    0
energy-kj_100g                 524215
energy-kcal_100g                53593
sugars_100g                      1660
saturated-fat_100g               1663
sodium_100g                      1243
fruits-vegetables-nuts_100g    609489
fiber_100g                     249140
proteins_100g                    1650
dtype: int64

In [10]:
#on consolide les colonnes que nous allons utiliser pour nos analsyes avec des colonnes complémentaires
#Le nom de notre produit peut être consolidé à partir de son nom générique et de sa marque
consolidation_name = products["generic_name"] + products["brands"]
#L'energie d'un produit en kJ est égal à son energie en kcal multiplié par 4,1868
consolidation_energy = products["energy-kcal_100g"].map(lambda x: x*4,1868)

#On remplace les valeurs manquantes
products["product_name"].fillna(consolidation_name, inplace=True)
products["energy-kj_100g"].fillna(consolidation_energy, inplace=True)

In [11]:
#Cette fonction permet de décompter les valeurs ayant le plus d'itérations au sein d'une colonne
def count_libelle(colonne, nb_most_common):
    
    words = []
    list_words = []
    for libelle in colonne:
        words += str(libelle).split(",")

    for word in (Counter(words).most_common(nb_most_common)):
        list_words.append((word[0].replace("en:","")).capitalize())
    
    return list_words

In [12]:
#On obtient ici la liste des 50 pays ayant le plus de produits
countries = count_libelle(products["countries_tags"].values, 60)

#si le tag est dans notre liste, on affecte le pays sinon on affecte la valeur AUTRE
column_country = [str(m).replace("en:","").capitalize() if (str(m).replace("en:","")).capitalize() in countries else "Autre" for m in products["countries_tags"]]
products.loc[:,"countries"] = column_country

In [13]:
#On obtient ici la liste des 500 catégories principales ayant le plus de produits
main_categories = count_libelle(products["main_category_en"].values, 500)

#si le tag est dans notre liste, on affecte la catégorie principale sinon on affecte la valeur AUTRE
column_main_category = [str(m).strip().capitalize() if str(m).strip().capitalize() in main_categories else "Autre" for m in products["main_category_en"]]
products.loc[:,"main_categories"] = column_main_category

In [14]:
#On obtient ici la liste des 1000 catégories secondaires ayant le plus de produits
categories = count_libelle(products["categories_en"].values, 1000)
#On retire la valeur NaN de la liste
categories = categories[1:]

#si le tag est dans notre liste, on affecte la catégorie secondaire sinon on affecte la valeur AUTRE
column_category = [str(m).split(",")[0] if str(m).split(",")[0] in categories else "Autre" for m in products["categories_en"]]
products.loc[:,"categories"] = column_category

In [15]:
#On regarde le nombre de valeur nulle
products.isnull().sum()

code                                0
created_datetime                    0
product_name                     2304
generic_name                   532199
brands                         171093
countries_tags                    765
categories_en                       2
main_category_en                    2
nutriscore_score                    0
nutriscore_grade                    0
energy-kj_100g                   1694
energy-kcal_100g                53593
sugars_100g                      1660
saturated-fat_100g               1663
sodium_100g                      1243
fruits-vegetables-nuts_100g    609489
fiber_100g                     249140
proteins_100g                    1650
countries                           0
main_categories                     0
categories                          0
dtype: int64

In [16]:
#Nous avons maintenant nos colonnes pour l'analyse
#On ne garde pas fruits-vegetables-nuts_100g car la colonne est est vide à 98%
#On ne garde pas fiber_100g car la colonne est est vide à 98%
products_optimized = products[['code', 'created_datetime', 'product_name','countries','main_categories','categories'
                              ,'nutriscore_score', 'nutriscore_grade', 'energy-kj_100g', 'sugars_100g'
                              , 'saturated-fat_100g', 'sodium_100g', 'fiber_100g', 'proteins_100g']]

#On décide de ne pas supprimer les lignes ayant un product_name null car on ne va pas utiliser la valeur pour l'analyse
#Pour les autres valeurs on supprime les lignes
products_optimized = products_optimized.dropna(subset = ['energy-kj_100g','sugars_100g','saturated-fat_100g'
                                                         ,'sodium_100g','fiber_100g','proteins_100g'])

In [17]:
#Le nutriscore est une valeur comprise entre -15 et 40
products_optimized = products_optimized[(products_optimized["nutriscore_score"] >= -15) & (products_optimized["nutriscore_score"] <= 40)]
#Le nutriscore est également une valeur égale à : a, b, c, d ou e
products_optimized = products_optimized[products_optimized["nutriscore_grade"].isin(['a', 'b', 'c', 'd', 'e'])]

#On enlève les valeurs abberantes d'énergie (en Kj) qui sont négatives, nulles ou supérieures à 3000 Kj 
products_optimized = products_optimized[(products_optimized["energy-kj_100g"] > 0) & (products_optimized["energy-kj_100g"] <= 3000)]

#La valeur étant donné pour 100g, elle est comprise entre 0 et 100
products_optimized = products_optimized[(products_optimized["sugars_100g"] >= 0) & (products_optimized["sugars_100g"] <= 50)]
products_optimized = products_optimized[(products_optimized["saturated-fat_100g"] >= 0) & (products_optimized["saturated-fat_100g"] <= 20)]
products_optimized = products_optimized[(products_optimized["sodium_100g"] >= 0) & (products_optimized["sodium_100g"] <= 10)]
products_optimized = products_optimized[(products_optimized["fiber_100g"] >= 0) & (products_optimized["fiber_100g"] <= 60)]
products_optimized = products_optimized[(products_optimized["proteins_100g"] >= 0) & (products_optimized["proteins_100g"] <= 90)]

In [18]:
#On regarde le nombre de valeur non nulle par colonne
products_optimized.notnull().sum()

code                  325973
created_datetime      325973
product_name          325056
countries             325973
main_categories       325973
categories            325973
nutriscore_score      325973
nutriscore_grade      325973
energy-kj_100g        325973
sugars_100g           325973
saturated-fat_100g    325973
sodium_100g           325973
fiber_100g            325973
proteins_100g         325973
dtype: int64

In [ ]:
#On enregistre le jeu de données nettoyé sous format pickle
products_optimized.to_pickle("products_optimized")